language: php
php:
    - '7.2'
    - '7.4snapshot'

matrix:
    include:
        -   name: 'Lowest dependencies'
            php: '7.2'
            env: DEPENDENCIES="--prefer-lowest"
        -   name: 'Codestyle and static analysis'
            php: '7.3'
            env: CHECK_CODESTYLE=1
            before_install: phpenv config-rm xdebug.ini
            script: composer analyze
        -   name: 'Tests on 7.3'
            php: '7.3'
            script: composer tests-ci
            after_success: travis_retry php vendor/bin/php-coveralls -v

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer update --no-interaction $DEPENDENCIES

script:
    - composer tests-ci

cache:
    directories:
        - $HOME/.composer/cache
